### ISSUE TITLE
Implement distributed cache option

### ISSUE THREAD

**Issue by IshamMohamed** [IshamMohamed/synca#9]
Currently caching is done via `IMemoryCache`. Give an option for the users to configure distributed caching

- [x]  [Distributed Memory Cache](https://github.com/IshamMohamed/synca/issues/10)
- [x]  [Distributed SQL Server cache](https://github.com/IshamMohamed/synca/issues/11)
- [ ]  [Distributed Redis cache](https://github.com/IshamMohamed/synca/issues/12)
- [ ]  [Distributed NCache cache](https://github.com/IshamMohamed/synca/issues/13)
